/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('rpc', 'meta', {
  "welcomeToPikku": "welcomeToPikku",
  "helloWorld": "helloWorld",
  "rpcTest": "rpcTest",
  "rpcCaller": "rpcCaller",
  "flakyHappyRPC": "flakyHappyRPC",
  "happyRetryWorkflow": "happyRetryWorkflow",
  "happyRetry": "happyRetry",
  "alwaysFailsRPC": "alwaysFailsRPC",
  "unhappyRetryWorkflow": "unhappyRetryWorkflow",
  "unhappyRetry": "unhappyRetry",
  "createUserProfile": "createUserProfile",
  "sendEmail": "sendEmail",
  "onboardingWorkflow": "onboardingWorkflow",
  "triggerOnboardingWorkflow": "triggerOnboardingWorkflow"
})