/**
 * This file was generated by @pikku/cli@0.11.1
 */
/**
 * This provides the structure needed for typescript to be aware of RPCs and their return types
 */
    


// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type RpcTestInput = { in: number; }
export type RpcCallerInput = { name: string; data?: any; }
export type FlakyHappyRPCInput = { value: number; }
export type FlakyHappyRPCOutput = { result: number; attempt: number; }
export type HappyRetryWorkflowInput = { value: number; }
export type HappyRetryWorkflowOutput = { result: number; finalAttempt: number; message: string; }
export type HappyRetryInput = { value: number; }
export type HappyRetryOutput = { result: number; finalAttempt: number; message: string; steps: { stepName: string; status: string; attemptCount: number; error?: { message: string; }; }[]; }
export type AlwaysFailsRPCInput = { value: number; }
export type AlwaysFailsRPCOutput = { result: number; }
export type UnhappyRetryWorkflowInput = { value: number; }
export type UnhappyRetryWorkflowOutput = { result: number; }
export type UnhappyRetryInput = { value: number; }
export type UnhappyRetryOutput = { error: string; attempts: number; steps: { stepName: string; status: string; attemptCount: number; error?: { message: string; }; }[]; }
export type CreateUserProfileInput = { email: string; userId: string; }
export type CreateUserProfileOutput = { id: string; email: string; name: string; createdAt: string; }
export type SendEmailInput = { to: string; subject: string; body: string; }
export type SendEmailOutput = { sent: boolean; messageId: string; to: string; }
export type OnboardingWorkflowInput = { email: string; userId: string; }
export type OnboardingWorkflowOutput = { userId: string; email: string; }
export type TriggerOnboardingWorkflowInput = { email: string; userId: string; }

interface RPCHandler<I, O> {
    input: I;
    output: O;
}

export type RPCMap = {
  readonly 'welcomeToPikku': RPCHandler<null, string>,
  readonly 'helloWorld': RPCHandler<null, string>,
  readonly 'rpcTest': RPCHandler<RpcTestInput, null>,
  readonly 'rpcCaller': RPCHandler<RpcCallerInput, null>,
  readonly 'flakyHappyRPC': RPCHandler<FlakyHappyRPCInput, FlakyHappyRPCOutput>,
  readonly 'happyRetryWorkflow': RPCHandler<HappyRetryWorkflowInput, HappyRetryWorkflowOutput>,
  readonly 'happyRetry': RPCHandler<HappyRetryInput, HappyRetryOutput>,
  readonly 'alwaysFailsRPC': RPCHandler<AlwaysFailsRPCInput, AlwaysFailsRPCOutput>,
  readonly 'unhappyRetryWorkflow': RPCHandler<UnhappyRetryWorkflowInput, UnhappyRetryWorkflowOutput>,
  readonly 'unhappyRetry': RPCHandler<UnhappyRetryInput, UnhappyRetryOutput>,
  readonly 'createUserProfile': RPCHandler<CreateUserProfileInput, CreateUserProfileOutput>,
  readonly 'sendEmail': RPCHandler<SendEmailInput, SendEmailOutput>,
  readonly 'onboardingWorkflow': RPCHandler<OnboardingWorkflowInput, OnboardingWorkflowOutput>,
  readonly 'triggerOnboardingWorkflow': RPCHandler<TriggerOnboardingWorkflowInput, null>,
};


export type RPCInvoke = <Name extends keyof RPCMap>(
  name: Name,
  data: RPCMap[Name]['input'],
  options?: {
    location?: 'local' | 'remote' | 'auto'
  }
) => Promise<RPCMap[Name]['output']>

// Import WorkflowMap for workflow typing
import type { WorkflowMap } from '../workflow/pikku-workflow-map.gen.js'

export type TypedPikkuRPC = {
  depth: number;
  global: boolean;
  invoke: RPCInvoke;
  invokeExposed: (name: string, data: any) => Promise<any>;
  startWorkflow: <Name extends keyof WorkflowMap>(
    name: Name,
    input: WorkflowMap[Name]['input']
  ) => Promise<{ runId: string }>;
}
  