/**
 * This file was generated by @pikku/cli@0.11.2
 */
/**
 * This provides the structure needed for typescript to be aware of RPCs and their return types
 */
    


// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type RpcTestInput = { in: number; }
export type RpcCallerInput = { rpcName: string; data?: any; }
export type PikkuFn_rpc_wiring_ts_L30C9Input = { rpcName: string; }
export type FlakyHappyRPCInput = { value: number; }
export type FlakyHappyRPCOutput = { result: number; attempt: number; }
export type HappyRetryWorkflowInput = { value: number; }
export type HappyRetryWorkflowOutput = { result: number; finalAttempt: number; message: string; }
export type HappyRetryInput = { value: number; }
export type HappyRetryOutput = { result: number; finalAttempt: number; message: string; steps: { stepName: string; status: string; attemptCount: number; error?: { message: string; }; }[]; }
export type CreateOrgInput = { name: string; }
export type CreateOrgOutput = { id: string; name: string; createdAt: string; }
export type CreateOwnerInput = { orgId: string; email: string; }
export type CreateOwnerOutput = { id: string; orgId: string; email: string; }
export type InviteMemberInput = { orgId: string; email: string; }
export type InviteMemberOutput = { id: string; email: string; status: string; }
export type SendWelcomeEmailInput = { to: string; orgId: string; }
export type SendWelcomeEmailOutput = { sent: boolean; messageId: string; }
export type OrgOnboardingSimpleWorkflowInput = { email: string; name: string; plan: string; memberEmails: string[]; }
export type OrgOnboardingSimpleWorkflowOutput = { orgId: string; ownerId?: string; }
export type SequentialInviteSimpleWorkflowInput = { orgId: string; memberEmails: string[]; delayMs: number; }
export type SequentialInviteSimpleWorkflowOutput = { invitedCount: number; }
export type TriggerOrgOnboardingSimpleInput = { email: string; name: string; plan: string; memberEmails: string[]; }
export type TriggerOrgOnboardingSimpleOutput = { orgId: string; ownerId?: string; runId: string; }
export type TriggerSequentialInviteSimpleInput = { orgId: string; memberEmails: string[]; delayMs: number; }
export type TriggerSequentialInviteSimpleOutput = { invitedCount: number; runId: string; }
export type AlwaysFailsRPCInput = { value: number; }
export type AlwaysFailsRPCOutput = { result: number; }
export type UnhappyRetryWorkflowInput = { value: number; }
export type UnhappyRetryWorkflowOutput = { result: number; }
export type UnhappyRetryInput = { value: number; }
export type UnhappyRetryOutput = { error: string; attempts: number; steps: { stepName: string; status: string; attemptCount: number; error?: { message: string; }; }[]; }
export type CreateUserProfileInput = { email: string; userId: string; }
export type CreateUserProfileOutput = { id: string; email: string; name: string; createdAt: string; }
export type SendEmailInput = { to: string; subject: string; body: string; }
export type SendEmailOutput = { sent: boolean; messageId: string; to: string; }
export type OnboardingWorkflowInput = { email: string; userId: string; }
export type OnboardingWorkflowOutput = { userId: string; email: string; }
export type TriggerOnboardingWorkflowInput = { email: string; userId: string; }

interface RPCHandler<I, O> {
    input: I;
    output: O;
}

export type RPCMap = {
  readonly 'rpcTest': RPCHandler<RpcTestInput, null>,
};


export type RPCInvoke = <Name extends keyof RPCMap>(
  name: Name,
  data: RPCMap[Name]['input'],
  options?: {
    location?: 'local' | 'remote' | 'auto'
  }
) => Promise<RPCMap[Name]['output']>

// Import WorkflowMap for workflow typing
import type { WorkflowMap } from '../workflow/pikku-workflow-map.gen.js'

export type TypedPikkuRPC = {
  depth: number;
  global: boolean;
  invoke: RPCInvoke;
  invokeExposed: (name: string, data: any) => Promise<any>;
  startWorkflow: <Name extends keyof WorkflowMap>(
    name: Name,
    input: WorkflowMap[Name]['input']
  ) => Promise<{ runId: string }>;
}
  