/**
 * This file was generated by @pikku/cli@0.11.2
 */
/**
 * Auto-generated workflow registrations
 * Do not edit manually - regenerate with 'npx pikku'
 */
import { addWorkflow } from '@pikku/core/workflow'

import { happyRetryWorkflow } from '../../src/workflow-happy.functions.js'
import { onboardingWorkflow } from '../../src/workflow.functions.js'
import { orgOnboardingSimpleWorkflow } from '../../src/workflow-simple.functions.js'
import { sequentialInviteSimpleWorkflow } from '../../src/workflow-simple.functions.js'
import { unhappyRetryWorkflow } from '../../src/workflow-unhappy.functions.js'

addWorkflow('happyRetryWorkflow', happyRetryWorkflow)
addWorkflow('onboardingWorkflow', onboardingWorkflow)
addWorkflow('orgOnboardingSimpleWorkflow', orgOnboardingSimpleWorkflow)
addWorkflow('sequentialInviteSimpleWorkflow', sequentialInviteSimpleWorkflow)
addWorkflow('unhappyRetryWorkflow', unhappyRetryWorkflow)
