/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('workflows', 'meta', {
  "onboarding": {
    "pikkuFuncName": "onboardingWorkflow",
    "workflowName": "onboarding",
    "description": "User onboarding workflow with email and profile setup",
    "tags": [
      "onboarding",
      "users"
    ],
    "steps": [
      {
        "type": "rpc",
        "stepName": "Create user profile in database for ${data.email}",
        "rpcName": "createUserProfile"
      },
      {
        "type": "inline",
        "stepName": "Generate personalized welcome message",
        "description": "<dynamic>"
      },
      {
        "type": "sleep",
        "stepName": "Sleeping for 5 seconds",
        "duration": "5s"
      },
      {
        "type": "rpc",
        "stepName": "Send welcome email to user",
        "rpcName": "sendEmail"
      }
    ]
  },
  "happyRetry": {
    "pikkuFuncName": "happyRetryWorkflow",
    "workflowName": "happyRetry",
    "description": "HAPPY PATH: Workflow that fails once then succeeds on retry",
    "tags": [
      "test",
      "retry",
      "happy"
    ],
    "steps": [
      {
        "type": "rpc",
        "stepName": "Step that fails once then succeeds",
        "rpcName": "flakyHappyRPC"
      }
    ]
  },
  "unhappyRetry": {
    "pikkuFuncName": "unhappyRetryWorkflow",
    "workflowName": "unhappyRetry",
    "description": "UNHAPPY PATH: Workflow that exhausts retries and fails",
    "tags": [
      "test",
      "retry",
      "unhappy"
    ],
    "steps": [
      {
        "type": "rpc",
        "stepName": "Step that always fails",
        "rpcName": "alwaysFailsRPC"
      }
    ]
  }
})
export type WorkflowNames = 'onboarding' | 'happyRetry' | 'unhappyRetry'