/**
 * This file was generated by @pikku/cli@0.11.1
 */
/**
 * This provides the structure needed for TypeScript to be aware of workflows and their input/output types
 */



// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type RpcTestInput = { in: number; }
export type RpcCallerInput = { name: string; data?: any; }
export type FlakyHappyRPCInput = { value: number; }
export type FlakyHappyRPCOutput = { result: number; attempt: number; }
export type HappyRetryWorkflowInput = { value: number; }
export type HappyRetryWorkflowOutput = { result: number; finalAttempt: number; message: string; }
export type HappyRetryInput = { value: number; }
export type HappyRetryOutput = { result: number; finalAttempt: number; message: string; steps: { stepName: string; status: string; attemptCount: number; error?: { message: string; }; }[]; }
export type AlwaysFailsRPCInput = { value: number; }
export type AlwaysFailsRPCOutput = { result: number; }
export type UnhappyRetryWorkflowInput = { value: number; }
export type UnhappyRetryWorkflowOutput = { result: number; }
export type UnhappyRetryInput = { value: number; }
export type UnhappyRetryOutput = { error: string; attempts: number; steps: { stepName: string; status: string; attemptCount: number; error?: { message: string; }; }[]; }
export type CreateUserProfileInput = { email: string; userId: string; }
export type CreateUserProfileOutput = { id: string; email: string; name: string; createdAt: string; }
export type SendEmailInput = { to: string; subject: string; body: string; }
export type SendEmailOutput = { sent: boolean; messageId: string; to: string; }
export type OnboardingWorkflowInput = { email: string; userId: string; }
export type OnboardingWorkflowOutput = { userId: string; email: string; }
export type TriggerOnboardingWorkflowInput = { email: string; userId: string; }
export type PikkuWorkflowOrchestratorInput = { runId: string; }
export type PikkuWorkflowStepSleeperInput = { runId: string; stepId: string; }

interface WorkflowHandler<I, O> {
    input: I;
    output: O;
}

export type WorkflowMap = {
  readonly 'onboarding': WorkflowHandler<OnboardingWorkflowInput, OnboardingWorkflowOutput>,
  readonly 'happyRetry': WorkflowHandler<HappyRetryWorkflowInput, HappyRetryWorkflowOutput>,
  readonly 'unhappyRetry': WorkflowHandler<UnhappyRetryWorkflowInput, UnhappyRetryWorkflowOutput>,
};


/**
 * Type-safe workflow client API
 */
export type WorkflowClient<Name extends keyof WorkflowMap> = {
  /**
   * Start a new workflow run
   */
  start: (input: WorkflowMap[Name]['input']) => Promise<{ runId: string }>;

  /**
   * Get a workflow run by ID
   */
  getRun: <output extends keyof WorkflowMap[Name]>(runId: string) => Promise<WorkflowMap[Name][output]>;

  /**
   * Cancel a running workflow
   */
  cancelRun: (runId: string) => Promise<boolean>;
}

/**
 * Map of all registered workflows with type-safe client APIs
 */
export type TypedWorkflowClients = {
  [Name in keyof WorkflowMap]: WorkflowClient<Name>;
}
  