/**
 * This file was generated by @pikku/cli@0.11.2
 */
import type { SingletonServices } from '../types/application-types.d.js'
import type { Services } from '../types/application-types.d.js'

// Singleton services map: true if required, false if available but unused
export const requiredSingletonServices = {
  'config': true,
  'eventHub': false,
  'jwt': false,
  'logger': true,
  'queueService': false,
  'schedulerService': false,
  'schema': true,
  'secrets': false,
  'variables': true,
  'workflowService': true,
} as const

// Wire services map: true if required, false if available but unused
export const requiredWireServices = {
} as const

// Type exports
export type RequiredSingletonServices = Pick<SingletonServices, 'config' | 'logger' | 'schema' | 'variables' | 'workflowService'> & Partial<Omit<SingletonServices, 'config' | 'logger' | 'schema' | 'variables' | 'workflowService'>>

export type RequiredWireServices = Partial<Services>
