/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('http', 'meta', {
  "get": {
    "/": {
      "pikkuFuncName": "welcomeToPikku",
      "route": "/",
      "method": "get",
      "tags": [
        "welcome"
      ]
    },
    "/hello-world": {
      "pikkuFuncName": "helloWorld",
      "route": "/hello-world",
      "method": "get",
      "tags": [
        "hello"
      ]
    }
  },
  "post": {
    "/rpc": {
      "pikkuFuncName": "rpcCaller",
      "route": "/rpc",
      "method": "post"
    },
    "/workflow/start": {
      "pikkuFuncName": "triggerOnboardingWorkflow",
      "route": "/workflow/start",
      "method": "post",
      "tags": [
        "workflow"
      ]
    },
    "/workflow/test/happy-retry": {
      "pikkuFuncName": "happyRetry",
      "route": "/workflow/test/happy-retry",
      "method": "post",
      "tags": [
        "workflow",
        "test"
      ]
    },
    "/workflow/test/unhappy-retry": {
      "pikkuFuncName": "unhappyRetry",
      "route": "/workflow/test/unhappy-retry",
      "method": "post",
      "tags": [
        "workflow",
        "test"
      ]
    }
  },
  "put": {},
  "delete": {},
  "head": {},
  "patch": {},
  "options": {
    "/rpc": {
      "pikkuFuncName": "pikkuFn_rpc_wiring_ts_L35C9",
      "route": "/rpc",
      "method": "options"
    }
  }
})