/**
 * This file was generated by @pikku/cli@0.11.1
 */
/**
 * This provides the structure needed for typescript to be aware of routes and their return types
 */
    


// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type RpcTestInput = { in: number; }
export type RpcCallerInput = { name: string; data?: any; }
export type FlakyHappyRPCInput = { value: number; }
export type FlakyHappyRPCOutput = { result: number; attempt: number; }
export type HappyRetryWorkflowInput = { value: number; }
export type HappyRetryWorkflowOutput = { result: number; finalAttempt: number; message: string; }
export type HappyRetryInput = { value: number; }
export type HappyRetryOutput = { result: number; finalAttempt: number; message: string; steps: { stepName: string; status: string; attemptCount: number; error?: { message: string; }; }[]; }
export type AlwaysFailsRPCInput = { value: number; }
export type AlwaysFailsRPCOutput = { result: number; }
export type UnhappyRetryWorkflowInput = { value: number; }
export type UnhappyRetryWorkflowOutput = { result: number; }
export type UnhappyRetryInput = { value: number; }
export type UnhappyRetryOutput = { error: string; attempts: number; steps: { stepName: string; status: string; attemptCount: number; error?: { message: string; }; }[]; }
export type CreateUserProfileInput = { email: string; userId: string; }
export type CreateUserProfileOutput = { id: string; email: string; name: string; createdAt: string; }
export type SendEmailInput = { to: string; subject: string; body: string; }
export type SendEmailOutput = { sent: boolean; messageId: string; to: string; }
export type OnboardingWorkflowInput = { email: string; userId: string; }
export type OnboardingWorkflowOutput = { userId: string; email: string; }
export type TriggerOnboardingWorkflowInput = { email: string; userId: string; }

// The '& {}' is a workaround for not directly refering to a type since it confuses typescript
export type RpcCallerInputBody = RpcCallerInput & {}
export type TriggerOnboardingWorkflowInputBody = TriggerOnboardingWorkflowInput & {}
export type HappyRetryInputBody = HappyRetryInput & {}
export type UnhappyRetryInputBody = UnhappyRetryInput & {}

interface HTTPWiringHandler<I, O> {
    input: I;
    output: O;
}

export type HTTPWiringsMap = {
  readonly '/': {
    readonly GET: HTTPWiringHandler<null, string>,
  },
  readonly '/hello-world': {
    readonly GET: HTTPWiringHandler<null, string>,
  },
  readonly '/rpc': {
    readonly POST: HTTPWiringHandler<RpcCallerInput, null>,
    readonly OPTIONS: HTTPWiringHandler<null, null>,
  },
  readonly '/workflow/start': {
    readonly POST: HTTPWiringHandler<TriggerOnboardingWorkflowInput, null>,
  },
  readonly '/workflow/test/happy-retry': {
    readonly POST: HTTPWiringHandler<HappyRetryInput, HappyRetryOutput>,
  },
  readonly '/workflow/test/unhappy-retry': {
    readonly POST: HTTPWiringHandler<UnhappyRetryInput, UnhappyRetryOutput>,
  },
};

export type HTTPWiringHandlerOf<HTTPWiring extends keyof HTTPWiringsMap, Method extends keyof HTTPWiringsMap[HTTPWiring]> =
    HTTPWiringsMap[HTTPWiring][Method] extends { input: infer I; output: infer O }
        ? HTTPWiringHandler<I, O>
        : never;

export type HTTPWiringsWithMethod<Method extends string> = {
  [HTTPWiring in keyof HTTPWiringsMap]: Method extends keyof HTTPWiringsMap[HTTPWiring] ? HTTPWiring : never;
}[keyof HTTPWiringsMap];
  