/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('queue', 'meta', {
  "pikku-workflow-step-worker": {
    "pikkuFuncName": "pikkuWorkflowWorker",
    "queueName": "pikku-workflow-step-worker"
  },
  "pikku-workflow-orchestrator": {
    "pikkuFuncName": "pikkuWorkflowOrchestrator",
    "queueName": "pikku-workflow-orchestrator"
  },
  "pikku-remote-internal-rpc": {
    "pikkuFuncName": "pikkuRemoteInternalRPC",
    "queueName": "pikku-remote-internal-rpc"
  }
})