/**
 * This file was generated by @pikku/cli@0.11.2
 */
/**
 * This provides the structure needed for typescript to be aware of Queue workers and their input/output types
 */
    
import type { WorkflowStepInput } from '../../src/workflows/pikku.workflows.gen.js'

// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type RpcTestInput = { in: number; }
export type RpcCallerInput = { rpcName: string; data?: any; }
export type PikkuFn_rpc_wiring_ts_L30C9Input = { rpcName: string; }
export type FlakyHappyRPCInput = { value: number; }
export type FlakyHappyRPCOutput = { result: number; attempt: number; }
export type HappyRetryWorkflowInput = { value: number; }
export type HappyRetryWorkflowOutput = { result: number; finalAttempt: number; message: string; }
export type HappyRetryInput = { value: number; }
export type HappyRetryOutput = { result: number; finalAttempt: number; message: string; steps: { stepName: string; status: string; attemptCount: number; error?: { message: string; }; }[]; }
export type CreateOrgInput = { name: string; }
export type CreateOrgOutput = { id: string; name: string; createdAt: string; }
export type CreateOwnerInput = { orgId: string; email: string; }
export type CreateOwnerOutput = { id: string; orgId: string; email: string; }
export type InviteMemberInput = { orgId: string; email: string; }
export type InviteMemberOutput = { id: string; email: string; status: string; }
export type SendWelcomeEmailInput = { to: string; orgId: string; }
export type SendWelcomeEmailOutput = { sent: boolean; messageId: string; }
export type OrgOnboardingSimpleWorkflowInput = { email: string; name: string; plan: string; memberEmails: string[]; }
export type OrgOnboardingSimpleWorkflowOutput = { orgId: string; ownerId?: string; }
export type SequentialInviteSimpleWorkflowInput = { orgId: string; memberEmails: string[]; delayMs: number; }
export type SequentialInviteSimpleWorkflowOutput = { invitedCount: number; }
export type TriggerOrgOnboardingSimpleInput = { email: string; name: string; plan: string; memberEmails: string[]; }
export type TriggerOrgOnboardingSimpleOutput = { orgId: string; ownerId?: string; runId: string; }
export type TriggerSequentialInviteSimpleInput = { orgId: string; memberEmails: string[]; delayMs: number; }
export type TriggerSequentialInviteSimpleOutput = { invitedCount: number; runId: string; }
export type AlwaysFailsRPCInput = { value: number; }
export type AlwaysFailsRPCOutput = { result: number; }
export type UnhappyRetryWorkflowInput = { value: number; }
export type UnhappyRetryWorkflowOutput = { result: number; }
export type UnhappyRetryInput = { value: number; }
export type UnhappyRetryOutput = { error: string; attempts: number; steps: { stepName: string; status: string; attemptCount: number; error?: { message: string; }; }[]; }
export type CreateUserProfileInput = { email: string; userId: string; }
export type CreateUserProfileOutput = { id: string; email: string; name: string; createdAt: string; }
export type SendEmailInput = { to: string; subject: string; body: string; }
export type SendEmailOutput = { sent: boolean; messageId: string; to: string; }
export type OnboardingWorkflowInput = { email: string; userId: string; }
export type OnboardingWorkflowOutput = { userId: string; email: string; }
export type TriggerOnboardingWorkflowInput = { email: string; userId: string; }
export type PikkuWorkflowOrchestratorInput = { runId: string; }
export type PikkuWorkflowStepSleeperInput = { runId: string; stepId: string; }

import type { QueueJob } from '@pikku/core/queue'

interface QueueHandler<I, O> {
    input: I;
    output: O;
}

export type QueueMap = {
  readonly 'pikku-workflow-step-worker': QueueHandler<WorkflowStepInput, null>,
  readonly 'pikku-workflow-orchestrator': QueueHandler<PikkuWorkflowOrchestratorInput, null>,
};


type QueueAdd = <Name extends keyof QueueMap>(
  name: Name,
  data: QueueMap[Name]['input'],
  options?: {
    priority?: number
    delay?: number
    attempts?: number
    removeOnComplete?: number
    removeOnFail?: number
    jobId?: string
  }
) => Promise<string>

type QueueGetJob = <Name extends keyof QueueMap>(
  name: Name,
  jobId: string
) => Promise<QueueJob<QueueMap[Name]['input'], QueueMap[Name]['output']> | null>

export type TypedPikkuQueue = {
  add: QueueAdd;
  getJob: QueueGetJob;
}
  