/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "welcomeToPikku": {
    "pikkuFuncName": "welcomeToPikku",
    "inputSchemaName": null,
    "outputSchemaName": "string"
  },
  "helloWorld": {
    "pikkuFuncName": "helloWorld",
    "inputSchemaName": null,
    "outputSchemaName": "string"
  },
  "rpcTest": {
    "pikkuFuncName": "rpcTest",
    "inputSchemaName": "RpcTestInput",
    "outputSchemaName": null,
    "expose": true
  },
  "rpcCaller": {
    "pikkuFuncName": "rpcCaller",
    "inputSchemaName": "RpcCallerInput",
    "outputSchemaName": null
  },
  "pikkuFn_rpc_wiring_ts_L35C9": {
    "pikkuFuncName": "pikkuFn_rpc_wiring_ts_L35C9",
    "inputSchemaName": null,
    "outputSchemaName": null
  },
  "flakyHappyRPC": {
    "pikkuFuncName": "flakyHappyRPC",
    "inputSchemaName": "FlakyHappyRPCInput",
    "outputSchemaName": "FlakyHappyRPCOutput"
  },
  "happyRetryWorkflow": {
    "pikkuFuncName": "happyRetryWorkflow",
    "inputSchemaName": "HappyRetryWorkflowInput",
    "outputSchemaName": "HappyRetryWorkflowOutput"
  },
  "happyRetry": {
    "pikkuFuncName": "happyRetry",
    "inputSchemaName": "HappyRetryInput",
    "outputSchemaName": "HappyRetryOutput"
  },
  "alwaysFailsRPC": {
    "pikkuFuncName": "alwaysFailsRPC",
    "inputSchemaName": "AlwaysFailsRPCInput",
    "outputSchemaName": "AlwaysFailsRPCOutput"
  },
  "unhappyRetryWorkflow": {
    "pikkuFuncName": "unhappyRetryWorkflow",
    "inputSchemaName": "UnhappyRetryWorkflowInput",
    "outputSchemaName": "UnhappyRetryWorkflowOutput"
  },
  "unhappyRetry": {
    "pikkuFuncName": "unhappyRetry",
    "inputSchemaName": "UnhappyRetryInput",
    "outputSchemaName": "UnhappyRetryOutput"
  },
  "createUserProfile": {
    "pikkuFuncName": "createUserProfile",
    "inputSchemaName": "CreateUserProfileInput",
    "outputSchemaName": "CreateUserProfileOutput"
  },
  "sendEmail": {
    "pikkuFuncName": "sendEmail",
    "inputSchemaName": "SendEmailInput",
    "outputSchemaName": "SendEmailOutput"
  },
  "onboardingWorkflow": {
    "pikkuFuncName": "onboardingWorkflow",
    "inputSchemaName": "OnboardingWorkflowInput",
    "outputSchemaName": "OnboardingWorkflowOutput"
  },
  "triggerOnboardingWorkflow": {
    "pikkuFuncName": "triggerOnboardingWorkflow",
    "inputSchemaName": "TriggerOnboardingWorkflowInput",
    "outputSchemaName": null
  }
})