/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "welcomeToPikku": {
    "pikkuFuncName": "welcomeToPikku",
    "name": "welcomeToPikku",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": "string",
    "inputs": [],
    "outputs": [
      "string"
    ],
    "isDirectFunction": true
  },
  "helloWorld": {
    "pikkuFuncName": "helloWorld",
    "name": "helloWorld",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": "string",
    "inputs": [],
    "outputs": [
      "string"
    ],
    "isDirectFunction": true
  },
  "rpcTest": {
    "pikkuFuncName": "rpcTest",
    "name": "rpcTest",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "rpc"
      ]
    },
    "inputSchemaName": "RpcTestInput",
    "outputSchemaName": null,
    "inputs": [
      "RpcTestInput"
    ],
    "outputs": [],
    "expose": true,
    "isDirectFunction": false
  },
  "rpcCaller": {
    "pikkuFuncName": "rpcCaller",
    "name": "rpcCaller",
    "services": {
      "optimized": true,
      "services": [
        "rpc"
      ]
    },
    "inputSchemaName": "RpcCallerInput",
    "outputSchemaName": null,
    "inputs": [
      "RpcCallerInput"
    ],
    "outputs": [],
    "isDirectFunction": false
  },
  "pikkuFn_rpc_wiring_ts_L35C9": {
    "pikkuFuncName": "pikkuFn_rpc_wiring_ts_L35C9",
    "name": "pikkuFn_rpc_wiring_ts_L35C9",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": null,
    "inputs": [],
    "outputs": [],
    "isDirectFunction": true
  },
  "flakyHappyRPC": {
    "pikkuFuncName": "flakyHappyRPC",
    "name": "flakyHappyRPC",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "workflowStep"
      ]
    },
    "inputSchemaName": "FlakyHappyRPCInput",
    "outputSchemaName": "FlakyHappyRPCOutput",
    "inputs": [
      "FlakyHappyRPCInput"
    ],
    "outputs": [
      "FlakyHappyRPCOutput"
    ],
    "isDirectFunction": false
  },
  "happyRetryWorkflow": {
    "pikkuFuncName": "happyRetryWorkflow",
    "name": "happyRetryWorkflow",
    "services": {
      "optimized": true,
      "services": [
        "workflow"
      ]
    },
    "inputSchemaName": "HappyRetryWorkflowInput",
    "outputSchemaName": "HappyRetryWorkflowOutput",
    "inputs": [
      "HappyRetryWorkflowInput"
    ],
    "outputs": [
      "HappyRetryWorkflowOutput"
    ],
    "isDirectFunction": true
  },
  "happyRetry": {
    "pikkuFuncName": "happyRetry",
    "name": "happyRetry",
    "services": {
      "optimized": true,
      "services": [
        "rpc",
        "workflowService",
        "logger"
      ]
    },
    "inputSchemaName": "HappyRetryInput",
    "outputSchemaName": "HappyRetryOutput",
    "inputs": [
      "HappyRetryInput"
    ],
    "outputs": [
      "HappyRetryOutput"
    ],
    "isDirectFunction": false
  },
  "alwaysFailsRPC": {
    "pikkuFuncName": "alwaysFailsRPC",
    "name": "alwaysFailsRPC",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "workflowStep"
      ]
    },
    "inputSchemaName": "AlwaysFailsRPCInput",
    "outputSchemaName": "AlwaysFailsRPCOutput",
    "inputs": [
      "AlwaysFailsRPCInput"
    ],
    "outputs": [
      "AlwaysFailsRPCOutput"
    ],
    "isDirectFunction": false
  },
  "unhappyRetryWorkflow": {
    "pikkuFuncName": "unhappyRetryWorkflow",
    "name": "unhappyRetryWorkflow",
    "services": {
      "optimized": true,
      "services": [
        "workflow"
      ]
    },
    "inputSchemaName": "UnhappyRetryWorkflowInput",
    "outputSchemaName": "UnhappyRetryWorkflowOutput",
    "inputs": [
      "UnhappyRetryWorkflowInput"
    ],
    "outputs": [
      "UnhappyRetryWorkflowOutput"
    ],
    "isDirectFunction": true
  },
  "unhappyRetry": {
    "pikkuFuncName": "unhappyRetry",
    "name": "unhappyRetry",
    "services": {
      "optimized": true,
      "services": [
        "rpc",
        "workflowService",
        "logger"
      ]
    },
    "inputSchemaName": "UnhappyRetryInput",
    "outputSchemaName": "UnhappyRetryOutput",
    "inputs": [
      "UnhappyRetryInput"
    ],
    "outputs": [
      "UnhappyRetryOutput"
    ],
    "isDirectFunction": false
  },
  "createUserProfile": {
    "pikkuFuncName": "createUserProfile",
    "name": "createUserProfile",
    "services": {
      "optimized": true,
      "services": [
        "logger"
      ]
    },
    "inputSchemaName": "CreateUserProfileInput",
    "outputSchemaName": "CreateUserProfileOutput",
    "inputs": [
      "CreateUserProfileInput"
    ],
    "outputs": [
      "CreateUserProfileOutput"
    ],
    "isDirectFunction": true
  },
  "sendEmail": {
    "pikkuFuncName": "sendEmail",
    "name": "sendEmail",
    "services": {
      "optimized": true,
      "services": [
        "logger"
      ]
    },
    "inputSchemaName": "SendEmailInput",
    "outputSchemaName": "SendEmailOutput",
    "inputs": [
      "SendEmailInput"
    ],
    "outputs": [
      "SendEmailOutput"
    ],
    "isDirectFunction": true
  },
  "onboardingWorkflow": {
    "pikkuFuncName": "onboardingWorkflow",
    "name": "onboardingWorkflow",
    "services": {
      "optimized": true,
      "services": [
        "workflow"
      ]
    },
    "inputSchemaName": "OnboardingWorkflowInput",
    "outputSchemaName": "OnboardingWorkflowOutput",
    "inputs": [
      "OnboardingWorkflowInput"
    ],
    "outputs": [
      "OnboardingWorkflowOutput"
    ],
    "isDirectFunction": true
  },
  "triggerOnboardingWorkflow": {
    "pikkuFuncName": "triggerOnboardingWorkflow",
    "name": "triggerOnboardingWorkflow",
    "services": {
      "optimized": true,
      "services": [
        "rpc",
        "workflowService",
        "logger"
      ]
    },
    "inputSchemaName": "TriggerOnboardingWorkflowInput",
    "outputSchemaName": null,
    "inputs": [
      "TriggerOnboardingWorkflowInput"
    ],
    "outputs": [],
    "isDirectFunction": true
  }
})