/**
 * This file was generated by @pikku/cli@0.11.1
 */
/* Import and register functions used by RPCs */
import { addFunction } from '@pikku/core'
import { alwaysFailsRPC } from '../../src/workflow-unhappy.functions.js'
import { createUserProfile } from '../../src/workflow.functions.js'
import { flakyHappyRPC } from '../../src/workflow-happy.functions.js'
import { rpcTest } from '../../src/rpc.functions.js'
import { sendEmail } from '../../src/workflow.functions.js'

addFunction('alwaysFailsRPC', alwaysFailsRPC)
addFunction('createUserProfile', createUserProfile)
addFunction('flakyHappyRPC', flakyHappyRPC)
addFunction('rpcTest', rpcTest)
addFunction('sendEmail', sendEmail)