/**
 * This file was generated by @pikku/cli@0.11.2
 */
/* Import and register functions used by RPCs */
import { addFunction } from '@pikku/core'
import { alwaysFailsRPC } from '../../src/workflow-unhappy.functions.js'
import { createOrg } from '../../src/workflow-simple.functions.js'
import { createOwner } from '../../src/workflow-simple.functions.js'
import { createUserProfile } from '../../src/workflow.functions.js'
import { flakyHappyRPC } from '../../src/workflow-happy.functions.js'
import { inviteMember } from '../../src/workflow-simple.functions.js'
import { rpcTest } from '../../src/rpc.functions.js'
import { sendEmail } from '../../src/workflow.functions.js'
import { sendWelcomeEmail } from '../../src/workflow-simple.functions.js'

addFunction('alwaysFailsRPC', alwaysFailsRPC)
addFunction('createOrg', createOrg)
addFunction('createOwner', createOwner)
addFunction('createUserProfile', createUserProfile)
addFunction('flakyHappyRPC', flakyHappyRPC)
addFunction('inviteMember', inviteMember)
addFunction('rpcTest', rpcTest)
addFunction('sendEmail', sendEmail)
addFunction('sendWelcomeEmail', sendWelcomeEmail)