/**
 * This file was generated by @pikku/cli@0.11.2
 */
import { addSchema } from '@pikku/core/schema'

import * as RpcTestInput from './schemas/RpcTestInput.schema.json' with { type: 'json' }
addSchema('RpcTestInput', RpcTestInput)


import * as RpcCallerInput from './schemas/RpcCallerInput.schema.json' with { type: 'json' }
addSchema('RpcCallerInput', RpcCallerInput)


import * as PikkuFn_rpc_wiring_ts_L30C9Input from './schemas/PikkuFn_rpc_wiring_ts_L30C9Input.schema.json' with { type: 'json' }
addSchema('PikkuFn_rpc_wiring_ts_L30C9Input', PikkuFn_rpc_wiring_ts_L30C9Input)


import * as FlakyHappyRPCInput from './schemas/FlakyHappyRPCInput.schema.json' with { type: 'json' }
addSchema('FlakyHappyRPCInput', FlakyHappyRPCInput)


import * as FlakyHappyRPCOutput from './schemas/FlakyHappyRPCOutput.schema.json' with { type: 'json' }
addSchema('FlakyHappyRPCOutput', FlakyHappyRPCOutput)


import * as HappyRetryWorkflowInput from './schemas/HappyRetryWorkflowInput.schema.json' with { type: 'json' }
addSchema('HappyRetryWorkflowInput', HappyRetryWorkflowInput)


import * as HappyRetryWorkflowOutput from './schemas/HappyRetryWorkflowOutput.schema.json' with { type: 'json' }
addSchema('HappyRetryWorkflowOutput', HappyRetryWorkflowOutput)


import * as HappyRetryInput from './schemas/HappyRetryInput.schema.json' with { type: 'json' }
addSchema('HappyRetryInput', HappyRetryInput)


import * as HappyRetryOutput from './schemas/HappyRetryOutput.schema.json' with { type: 'json' }
addSchema('HappyRetryOutput', HappyRetryOutput)


import * as CreateOrgInput from './schemas/CreateOrgInput.schema.json' with { type: 'json' }
addSchema('CreateOrgInput', CreateOrgInput)


import * as CreateOrgOutput from './schemas/CreateOrgOutput.schema.json' with { type: 'json' }
addSchema('CreateOrgOutput', CreateOrgOutput)


import * as CreateOwnerInput from './schemas/CreateOwnerInput.schema.json' with { type: 'json' }
addSchema('CreateOwnerInput', CreateOwnerInput)


import * as CreateOwnerOutput from './schemas/CreateOwnerOutput.schema.json' with { type: 'json' }
addSchema('CreateOwnerOutput', CreateOwnerOutput)


import * as InviteMemberInput from './schemas/InviteMemberInput.schema.json' with { type: 'json' }
addSchema('InviteMemberInput', InviteMemberInput)


import * as InviteMemberOutput from './schemas/InviteMemberOutput.schema.json' with { type: 'json' }
addSchema('InviteMemberOutput', InviteMemberOutput)


import * as SendWelcomeEmailInput from './schemas/SendWelcomeEmailInput.schema.json' with { type: 'json' }
addSchema('SendWelcomeEmailInput', SendWelcomeEmailInput)


import * as SendWelcomeEmailOutput from './schemas/SendWelcomeEmailOutput.schema.json' with { type: 'json' }
addSchema('SendWelcomeEmailOutput', SendWelcomeEmailOutput)


import * as OrgOnboardingSimpleWorkflowInput from './schemas/OrgOnboardingSimpleWorkflowInput.schema.json' with { type: 'json' }
addSchema('OrgOnboardingSimpleWorkflowInput', OrgOnboardingSimpleWorkflowInput)


import * as OrgOnboardingSimpleWorkflowOutput from './schemas/OrgOnboardingSimpleWorkflowOutput.schema.json' with { type: 'json' }
addSchema('OrgOnboardingSimpleWorkflowOutput', OrgOnboardingSimpleWorkflowOutput)


import * as SequentialInviteSimpleWorkflowInput from './schemas/SequentialInviteSimpleWorkflowInput.schema.json' with { type: 'json' }
addSchema('SequentialInviteSimpleWorkflowInput', SequentialInviteSimpleWorkflowInput)


import * as SequentialInviteSimpleWorkflowOutput from './schemas/SequentialInviteSimpleWorkflowOutput.schema.json' with { type: 'json' }
addSchema('SequentialInviteSimpleWorkflowOutput', SequentialInviteSimpleWorkflowOutput)


import * as TriggerOrgOnboardingSimpleInput from './schemas/TriggerOrgOnboardingSimpleInput.schema.json' with { type: 'json' }
addSchema('TriggerOrgOnboardingSimpleInput', TriggerOrgOnboardingSimpleInput)


import * as TriggerOrgOnboardingSimpleOutput from './schemas/TriggerOrgOnboardingSimpleOutput.schema.json' with { type: 'json' }
addSchema('TriggerOrgOnboardingSimpleOutput', TriggerOrgOnboardingSimpleOutput)


import * as TriggerSequentialInviteSimpleInput from './schemas/TriggerSequentialInviteSimpleInput.schema.json' with { type: 'json' }
addSchema('TriggerSequentialInviteSimpleInput', TriggerSequentialInviteSimpleInput)


import * as TriggerSequentialInviteSimpleOutput from './schemas/TriggerSequentialInviteSimpleOutput.schema.json' with { type: 'json' }
addSchema('TriggerSequentialInviteSimpleOutput', TriggerSequentialInviteSimpleOutput)


import * as AlwaysFailsRPCInput from './schemas/AlwaysFailsRPCInput.schema.json' with { type: 'json' }
addSchema('AlwaysFailsRPCInput', AlwaysFailsRPCInput)


import * as AlwaysFailsRPCOutput from './schemas/AlwaysFailsRPCOutput.schema.json' with { type: 'json' }
addSchema('AlwaysFailsRPCOutput', AlwaysFailsRPCOutput)


import * as UnhappyRetryWorkflowInput from './schemas/UnhappyRetryWorkflowInput.schema.json' with { type: 'json' }
addSchema('UnhappyRetryWorkflowInput', UnhappyRetryWorkflowInput)


import * as UnhappyRetryWorkflowOutput from './schemas/UnhappyRetryWorkflowOutput.schema.json' with { type: 'json' }
addSchema('UnhappyRetryWorkflowOutput', UnhappyRetryWorkflowOutput)


import * as UnhappyRetryInput from './schemas/UnhappyRetryInput.schema.json' with { type: 'json' }
addSchema('UnhappyRetryInput', UnhappyRetryInput)


import * as UnhappyRetryOutput from './schemas/UnhappyRetryOutput.schema.json' with { type: 'json' }
addSchema('UnhappyRetryOutput', UnhappyRetryOutput)


import * as CreateUserProfileInput from './schemas/CreateUserProfileInput.schema.json' with { type: 'json' }
addSchema('CreateUserProfileInput', CreateUserProfileInput)


import * as CreateUserProfileOutput from './schemas/CreateUserProfileOutput.schema.json' with { type: 'json' }
addSchema('CreateUserProfileOutput', CreateUserProfileOutput)


import * as SendEmailInput from './schemas/SendEmailInput.schema.json' with { type: 'json' }
addSchema('SendEmailInput', SendEmailInput)


import * as SendEmailOutput from './schemas/SendEmailOutput.schema.json' with { type: 'json' }
addSchema('SendEmailOutput', SendEmailOutput)


import * as OnboardingWorkflowInput from './schemas/OnboardingWorkflowInput.schema.json' with { type: 'json' }
addSchema('OnboardingWorkflowInput', OnboardingWorkflowInput)


import * as OnboardingWorkflowOutput from './schemas/OnboardingWorkflowOutput.schema.json' with { type: 'json' }
addSchema('OnboardingWorkflowOutput', OnboardingWorkflowOutput)


import * as TriggerOnboardingWorkflowInput from './schemas/TriggerOnboardingWorkflowInput.schema.json' with { type: 'json' }
addSchema('TriggerOnboardingWorkflowInput', TriggerOnboardingWorkflowInput)
